<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SHETTY" failures="1" tests="1" name="Default test(failed)" time="20.136" errors="0" timestamp="2023-01-30T17:05:26 IST">
  <testcase classname="Web_Shop.TestScript19" name="addProductReview" time="7.837">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Product review is not added expected [Product review is iw successfully added.] but found [Product review is successfully added.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Product review is not added expected [Product review is iw successfully added.] but found [Product review is successfully added.]
at Web_Shop.TestScript19.addProductReview(TestScript19.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addProductReview -->
</testsuite> <!-- Default test(failed) -->
